# Server configurations
server:
  broker: "amqp://guest:guest@localhost:5672/"

# Database credentials
database:
  server: "localhost"
  port: 1433
  user: "sa"
  pass: "xxxxxxx"
  dbname: "NewJoiner"